version: '2'
services:
  ui:
    build: ./ui
    volumes:
      - ./ui:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    environment:
      SERVER_HOST:'0.0.0.0'
      SERVER_PORT:3001
      MONGO_HOST:'0.0.0.0'
      MONGO_PORT:27017
  mongo:
    image: mongo
    ports:
      - '27017:27017'